apiVersion: v1
kind: Service

metadata:
  name: backend-service

spec:
  type: NodePort
  selector:
    app: backend

  ports:
  - protocol: TCP
    nodePort: 30037
    targetPort: 5000
    port: 5000
    

